### ISSUE TITLE
Question about ubuntu

### ISSUE THREAD

**Issue by nemo0526** [coder-wangzhen/AIC22-MCVT#1]
Hello! May I ask that what ubuntu version your using ? Is pytorch:20.11 only for ubuntu 18.04 ?

**Comment by coder-wangzhen** [comment]
Hi @nemo0526 , Thanks for your issue !

We use ubuntu 20.04 in this project. The image version in readme is written incorrectly and I have modified it to pytorch:21.09.  

Kind regards
